// <auto-generated />
namespace TodoBack.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class InitialR : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialR));
        
        string IMigrationMetadata.Id
        {
            get { return "202601270055187_InitialR"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
